"""Every router the application exposes, in one list.

Registered here rather than scattered through `main`, so adding an endpoint
group is one import and one entry — and so the full API surface is readable in
a single file.
"""

from app.api.routes import (
    alerts,
    auth,
    billing,
    cart,
    cart_recovery,
    catalogue,
    comparison,
    delivery,
    coupons,
    email,
    growth,
    membership,
    messaging,
    monitoring,
    orders,
    payments,
    payments_monitor,
    products,
    questions,
    reports,
    returns,
    reviews,
    shipping,
    site,
    support,
    support_admin,
    suppliers,
    wallet,
    wishlist,
)
from app.api.routes.admin import (
    catalogue as admin_catalogue,
    content as admin_content,
    customers as admin_customers,
    dashboard as admin_dashboard,
    orders as admin_orders,
    settings as admin_settings,
    uploads as admin_uploads,
)

all_routers = [
    # --- storefront ------------------------------------------------------
    auth.router,
    auth.account_router,
    products.router,
    catalogue.router,
    catalogue.collections_router,
    reviews.router,
    coupons.router,
    cart.router,
    cart_recovery.router,
    alerts.router,
    comparison.router,
    questions.router,
    wallet.router,
    wallet.account_router,
    wallet.checkout_router,
    growth.referral_router,
    growth.account_router,
    growth.flash_router,
    growth.bundle_router,
    growth.cart_bundle_router,
    monitoring.events_router,
    messaging.account_router,
    messaging.public_router,
    messaging.reorder_router,
    delivery.router,
    shipping.estimate_router,
    shipping.customer_router,
    shipping.webhook_router,
    wishlist.router,
    orders.router,
    returns.router,
    membership.router,
    support.router,
    email.account_router,
    billing.router,
    payments.router,
    site.router,
    # --- portal ----------------------------------------------------------
    auth.admin_auth_router,
    products.admin_router,
    admin_catalogue.router,
    admin_catalogue.inventory_router,
    admin_orders.router,
    returns.admin_router,
    membership.admin_router,
    support_admin.router,
    email.admin_router,
    email.invoice_router,
    admin_customers.router,
    admin_content.router,
    admin_content.marketing_router,
    admin_settings.router,
    admin_dashboard.router,
    admin_uploads.router,
    reports.router,
    billing.admin_router,
    delivery.admin_router,
    cart_recovery.admin_router,
    payments_monitor.admin_router,
    alerts.admin_router,
    questions.admin_router,
    wallet.admin_gift_router,
    wallet.admin_credit_router,
    wallet.admin_loyalty_router,
    growth.admin_referral_router,
    growth.admin_flash_router,
    growth.admin_bundle_router,
    monitoring.admin_analytics_router,
    monitoring.admin_audit_router,
    monitoring.admin_health_router,
    messaging.admin_notifications_router,
    messaging.admin_campaigns_router,
    messaging.admin_backups_router,
    shipping.admin_router,
    shipping.admin_order_router,
    shipping.providers_router,
    suppliers.suppliers_router,
    suppliers.supplier_products_router,
    suppliers.product_suppliers_router,
    suppliers.purchase_orders_router,
]
