"""Every router the application exposes, in one list.

Registered here rather than scattered through `main`, so adding an endpoint
group is one import and one entry — and so the full API surface is readable in
a single file.
"""

from app.api.routes import (
    alerts,
    auth,
    billing,
    cart,
    cart_recovery,
    catalogue,
    comparison,
    delivery,
    discovery,
    coupons,
    email,
    growth,
    identity,
    lookup,
    membership,
    messaging,
    monitoring,
    orders,
    packing,
    payments,
    payments_monitor,
    products,
    refunds,
    questions,
    reports,
    returns,
    reviews,
    search,
    segments,
    shipping,
    site,
    support,
    support_admin,
    suppliers,
    wallet,
    wishlist,
)
from app.api.routes.admin import (
    catalogue as admin_catalogue,
    content as admin_content,
    customers as admin_customers,
    dashboard as admin_dashboard,
    orders as admin_orders,
    settings as admin_settings,
    uploads as admin_uploads,
)

all_routers = [
    # --- storefront ------------------------------------------------------
    auth.router,
    auth.account_router,
    # Social sign-in, one-time codes, linked accounts, sessions (docs/authentication.md).
    identity.router,
    identity.account_router,
    products.router,
    # Search suggestions and click-through (docs/search-and-filters.md).
    search.router,
    catalogue.router,
    catalogue.collections_router,
    reviews.router,
    coupons.router,
    cart.router,
    cart_recovery.router,
    alerts.router,
    comparison.router,
    questions.router,
    wallet.router,
    wallet.account_router,
    wallet.checkout_router,
    growth.referral_router,
    growth.account_router,
    growth.flash_router,
    growth.bundle_router,
    growth.cart_bundle_router,
    monitoring.events_router,
    messaging.account_router,
    messaging.public_router,
    messaging.reorder_router,
    delivery.router,
    shipping.estimate_router,
    shipping.customer_router,
    shipping.webhook_router,
    wishlist.router,
    # Product discovery (docs/product-discovery.md).
    discovery.recently_viewed_router,
    discovery.saved_router,
    discovery.product_router,
    discovery.recommendations_router,
    orders.router,
    returns.router,
    # Partial refunds: the customer's refunds (docs/refunds.md).
    refunds.account_router,
    membership.router,
    support.router,
    email.account_router,
    billing.router,
    payments.router,
    site.router,
    # Find your own orders, invoices, returns… by ID (docs/id-lookup.md).
    lookup.account_router,
    # --- portal ----------------------------------------------------------
    auth.admin_auth_router,
    # Any record by its ID, with a short preview (docs/id-lookup.md).
    lookup.admin_router,
    identity.admin_router,
    products.admin_router,
    admin_catalogue.router,
    admin_catalogue.inventory_router,
    admin_orders.router,
    returns.admin_router,
    membership.admin_router,
    support_admin.router,
    email.admin_router,
    email.invoice_router,
    admin_customers.router,
    admin_content.router,
    admin_content.marketing_router,
    admin_settings.router,
    admin_dashboard.router,
    admin_uploads.router,
    reports.router,
    billing.admin_router,
    # Partial refunds (docs/refunds.md).
    refunds.admin_router,
    delivery.admin_router,
    discovery.admin_product_router,
    discovery.admin_size_guide_router,
    discovery.admin_discovery_router,
    cart_recovery.admin_router,
    payments_monitor.admin_router,
    alerts.admin_router,
    questions.admin_router,
    wallet.admin_gift_router,
    wallet.admin_credit_router,
    wallet.admin_loyalty_router,
    growth.admin_referral_router,
    growth.admin_flash_router,
    growth.admin_bundle_router,
    monitoring.admin_analytics_router,
    monitoring.admin_audit_router,
    monitoring.admin_health_router,
    messaging.admin_notifications_router,
    messaging.admin_campaigns_router,
    messaging.admin_backups_router,
    shipping.admin_router,
    shipping.admin_order_router,
    shipping.providers_router,
    # Packing and shipping labels (docs/packing-and-labels.md).
    packing.packing_router,
    packing.order_packing_router,
    packing.shipment_labels_router,
    packing.labels_router,
    packing.settings_router,
    suppliers.suppliers_router,
    suppliers.supplier_products_router,
    suppliers.product_suppliers_router,
    suppliers.purchase_orders_router,
    # Customer segmentation (docs/customer-segmentation.md).
    segments.router,
    # Search & filters: attributes, product attribute values, search analytics.
    search.attributes_router,
    search.product_attributes_router,
    search.admin_router,
]
