import { describe, expect, it } from "vitest";

import { supplier } from "@/test/suppliers-fixtures";

import {
  CODE_PATTERN,
  GSTIN_PATTERN,
  MAX_QUANTITY,
  PAN_PATTERN,
  acceptedOf,
  draftFromSupplier,
  emptyAddress,
  emptySupplierDraft,
  previewSubtotal,
  toPurchaseOrderInput,
  toReceiptInput,
  toSupplierInput,
  toSupplierProductInput,
  validatePurchaseOrder,
  validateReceipt,
  validateSupplier,
  validateSupplierProduct,
  type PoDraft,
  type PoLineDraft,
  type ReceiptDraft,
  type ReceiptLineDraft,
  type SupplierDraft,
  type SupplierProductDraft,
} from "./validation";

/* ---------------------------------------------------------------- supplier */

const validDraft = (overrides: Partial<SupplierDraft> = {}): SupplierDraft => ({ ...draftFromSupplier(supplier()), ...overrides });

describe("patterns", () => {
  it.each(["AB", "ANVI-TEX", "A1-2-3", "X".repeat(30)])("accepts the code %s", (code) => expect(CODE_PATTERN.test(code)).toBe(true));
  it.each(["A", "anvi-tex", "ANVI TEX", "ANVI_TEX", "X".repeat(31), ""])("rejects the code %j", (code) => expect(CODE_PATTERN.test(code)).toBe(false));

  it.each(["29ABCDE1234F1Z5", "07AAACB1234C1ZV", "27AAPFU0939F1ZV"])("accepts the GSTIN %s", (gstin) => expect(GSTIN_PATTERN.test(gstin)).toBe(true));
  it.each([
    "29ABCDE1234F1Z", // 14 characters
    "29ABCDE1234F1Z55", // 16
    "29abcde1234f1z5", // lower case
    "AAABCDE1234F1Z5", // state code not digits
    "29ABCDE1234F0Z5", // entity number 0
    "29ABCDE1234F1Y5", // 14th character not Z
    "29ABCD11234F1Z5", // PAN part malformed
  ])("rejects the GSTIN %s", (gstin) => expect(GSTIN_PATTERN.test(gstin)).toBe(false));

  it.each(["ABCDE1234F", "AAPFU0939F"])("accepts the PAN %s", (pan) => expect(PAN_PATTERN.test(pan)).toBe(true));
  it.each(["ABCDE1234", "ABCDE12345", "abcde1234f", "1BCDE1234F", "ABCDE1234FF"])("rejects the PAN %s", (pan) => expect(PAN_PATTERN.test(pan)).toBe(false));
});

describe("drafts", () => {
  it("starts empty, registered, in India and in rupees", () => {
    expect(emptySupplierDraft()).toMatchObject({
      code: "",
      name: "",
      taxTreatment: "registered",
      businessType: "manufacturer",
      creditDays: "0",
      currency: "INR",
      hasWarehouse: false,
      billingAddress: emptyAddress(),
    });
    expect(emptyAddress().country).toBe("India");
  });

  it("is built from a saved supplier, as text", () => {
    const draft = draftFromSupplier(supplier({ warehouseAddress: { line1: "Unit 4", line2: "", city: "Tiruppur", state: "Tamil Nadu", country: "India", pincode: "641601" } }));
    expect(draft).toMatchObject({ code: "ANVI-TEX", name: "Anvi Textiles", gstin: "29ABCDE1234F1Z5", creditDays: "30", hasWarehouse: true });
    expect(draft.warehouseAddress.city).toBe("Tiruppur");
  });

  it("fills in what a saved supplier is missing", () => {
    const sparse = supplier({ gstin: null, pan: null, warehouseAddress: null, currency: "", creditDays: undefined as unknown as number, billingAddress: null as never });
    const draft = draftFromSupplier(sparse);
    expect(draft.gstin).toBe("");
    expect(draft.pan).toBe("");
    expect(draft.hasWarehouse).toBe(false);
    expect(draft.currency).toBe("INR");
    expect(draft.creditDays).toBe("0");
    expect(draft.billingAddress).toEqual(emptyAddress());
  });
});

describe("validateSupplier", () => {
  it("accepts a complete, consistent supplier", () => {
    expect(validateSupplier(validDraft())).toEqual({});
  });

  it("needs only a name (and a GSTIN while registered)", () => {
    expect(validateSupplier({ ...emptySupplierDraft(), taxTreatment: "unregistered" })).toEqual({ name: "Enter the supplier's name." });
    expect(validateSupplier({ ...emptySupplierDraft(), name: "  " })).toEqual({
      name: "Enter the supplier's name.",
      gstin: "A registered supplier needs a GSTIN.",
    });
  });

  it.each(["unregistered", "composition", "overseas"] as const)("doesn't need a GSTIN for a %s supplier", (taxTreatment) => {
    expect(validateSupplier(validDraft({ taxTreatment, gstin: "", pan: "" }))).toEqual({});
  });

  it("checks a typed code, and allows a blank one (generated by the server)", () => {
    expect(validateSupplier(validDraft({ code: "" }))).toEqual({});
    expect(validateSupplier(validDraft({ code: "a b" })).code).toBe("Use 2–30 capital letters, digits or hyphens.");
    expect(validateSupplier(validDraft({ code: "  ANVI-2  " }))).toEqual({});
  });

  it("explains a malformed GSTIN, even for an unregistered supplier", () => {
    expect(validateSupplier(validDraft({ gstin: "29ABCDE1234F" })).gstin).toBe("A GSTIN is 15 characters, like 29ABCDE1234F1Z5.");
    expect(validateSupplier(validDraft({ taxTreatment: "unregistered", gstin: "BAD", pan: "" })).gstin).toBe(
      "A GSTIN is 15 characters, like 29ABCDE1234F1Z5.",
    );
  });

  it("checks the PAN's form and that it matches characters 3–12 of the GSTIN", () => {
    expect(validateSupplier(validDraft({ pan: "ABCDE1234" })).pan).toBe("A PAN is 10 characters, like ABCDE1234F.");
    expect(validateSupplier(validDraft({ pan: "ZZZZZ9999Z" })).pan).toBe("The PAN doesn't match characters 3–12 of the GSTIN.");
    expect(validateSupplier(validDraft({ pan: "" }))).toEqual({});
  });

  it("doesn't compare the PAN with a GSTIN that is itself wrong", () => {
    const errors = validateSupplier(validDraft({ gstin: "29ABCDE1234F0Z5", pan: "ZZZZZ9999Z" }));
    expect(errors.gstin).toBeDefined();
    expect(errors.pan).toBeUndefined();
  });

  it("checks a PAN without a GSTIN only for its form", () => {
    expect(validateSupplier(validDraft({ taxTreatment: "unregistered", gstin: "", pan: "ZZZZZ9999Z" }))).toEqual({});
  });

  it.each([
    ["sales@anvi", "Enter a valid email address."],
    ["sales anvi@x.co", "Enter a valid email address."],
    ["@anvi.example", "Enter a valid email address."],
  ])("rejects the email %s", (email, message) => {
    expect(validateSupplier(validDraft({ email })).email).toBe(message);
  });

  it.each(["9876543210", "98765 43210", "98765-43210", "+919876543210", "+4420712345"])("accepts the phone %s", (phone) => {
    expect(validateSupplier(validDraft({ phone })).phone).toBeUndefined();
  });

  it.each(["98765", "098765432101", "+0123456789", "phone", "+91 98"])("rejects the phone %s", (phone) => {
    expect(validateSupplier(validDraft({ phone })).phone).toBe("Enter a 10-digit number, or + and the country code.");
  });

  it.each([
    ["0", undefined],
    ["365", undefined],
    ["", undefined],
    ["366", "Credit days are a whole number from 0 to 365."],
    ["-1", "Credit days are a whole number from 0 to 365."],
    ["1.5", "Credit days are a whole number from 0 to 365."],
  ])("checks credit days of %j", (creditDays, message) => {
    expect(validateSupplier(validDraft({ creditDays })).creditDays).toBe(message);
  });

  it("needs a 6-digit pincode for an Indian billing address, under the API's field name", () => {
    const billing = (pincode: string, country = "India") => validDraft({ billingAddress: { ...emptyAddress(), country, pincode } });
    expect(validateSupplier(billing("56001"))["billingAddress.pincode"]).toBe("A pincode in India is 6 digits.");
    expect(validateSupplier(billing("56000A"))["billingAddress.pincode"]).toBe("A pincode in India is 6 digits.");
    expect(validateSupplier(billing(" 560001 "))["billingAddress.pincode"]).toBeUndefined();
    expect(validateSupplier(billing(""))["billingAddress.pincode"]).toBeUndefined();
    // Country is matched loosely; abroad any postcode goes.
    expect(validateSupplier(billing("56001", " india "))["billingAddress.pincode"]).toBeDefined();
    expect(validateSupplier(billing("SW1A 1AA", "United Kingdom"))["billingAddress.pincode"]).toBeUndefined();
  });

  it("checks the warehouse pincode only when there's a separate warehouse", () => {
    const warehouseAddress = { ...emptyAddress(), pincode: "123" };
    expect(validateSupplier(validDraft({ hasWarehouse: false, warehouseAddress }))).toEqual({});
    expect(validateSupplier(validDraft({ hasWarehouse: true, warehouseAddress }))).toEqual({
      "warehouseAddress.pincode": "A pincode in India is 6 digits.",
    });
  });
});

describe("toSupplierInput", () => {
  it("trims everything, leaves a blank code out and sends blank tax ids as null", () => {
    const input = toSupplierInput({
      ...emptySupplierDraft(),
      code: "  ",
      name: "  Anvi  ",
      gstin: "",
      pan: " ",
      creditDays: " ",
      billingAddress: { line1: " 12 Mill Road ", line2: "", city: " Bengaluru ", state: " Karnataka ", country: " India ", pincode: " 560001 " },
      warehouseAddress: { ...emptyAddress(), city: "Ignored" },
    });
    expect(input).not.toHaveProperty("code");
    expect(input).toMatchObject({
      name: "Anvi",
      gstin: null,
      pan: null,
      creditDays: 0,
      warehouseAddress: null,
      billingAddress: { line1: "12 Mill Road", line2: "", city: "Bengaluru", state: "Karnataka", country: "India", pincode: "560001" },
    });
  });

  it("sends the code, the warehouse and credit days as a number when given", () => {
    const input = toSupplierInput(validDraft({ code: " ANVI-TEX ", creditDays: "45", hasWarehouse: true, warehouseAddress: { ...emptyAddress(), city: " Tiruppur " } }));
    expect(input.code).toBe("ANVI-TEX");
    expect(input.creditDays).toBe(45);
    expect(input.warehouseAddress?.city).toBe("Tiruppur");
    expect(input.gstin).toBe("29ABCDE1234F1Z5");
  });
});

/* -------------------------------------------------------- supplier–product */

const link = (overrides: Partial<SupplierProductDraft> = {}): SupplierProductDraft => ({
  supplierSku: " AT-K-01 ",
  purchaseCost: "450",
  moq: "10",
  leadTimeDays: "7",
  status: "active",
  preferred: true,
  notes: " ",
  ...overrides,
});

describe("validateSupplierProduct", () => {
  it("accepts a valid link", () => {
    expect(validateSupplierProduct(link())).toEqual({});
    expect(validateSupplierProduct(link({ purchaseCost: "0.01", moq: "1", leadTimeDays: "" }))).toEqual({});
    expect(validateSupplierProduct(link({ purchaseCost: "10000000", leadTimeDays: "365" }))).toEqual({});
  });

  it.each(["", "0", "0.00", "-5", "4.555", "abc", " "])("needs a cost above zero, not %j", (purchaseCost) => {
    expect(validateSupplierProduct(link({ purchaseCost })).purchaseCost).toBe("Enter a cost above ₹0.");
  });

  it("caps the cost", () => {
    expect(validateSupplierProduct(link({ purchaseCost: "10000000.01" })).purchaseCost).toBe("The cost can be at most ₹1,00,00,000.");
  });

  it.each(["", "0", "1.5", "-1", "x"])("needs a whole minimum order of at least 1, not %j", (moq) => {
    expect(validateSupplierProduct(link({ moq })).moq).toBe("The minimum order is a whole number, at least 1.");
  });

  it.each(["366", "1.5", "-1", "a week"])("rejects a lead time of %j", (leadTimeDays) => {
    expect(validateSupplierProduct(link({ leadTimeDays })).leadTimeDays).toBe("Lead time is a whole number of days from 0 to 365, or blank.");
  });

  it("converts to numbers, with a blank lead time as null", () => {
    expect(toSupplierProductInput(link({ leadTimeDays: " " }))).toEqual({
      supplierSku: "AT-K-01",
      purchaseCost: 450,
      moq: 10,
      leadTimeDays: null,
      status: "active",
      preferred: true,
      notes: "",
    });
    expect(toSupplierProductInput(link()).leadTimeDays).toBe(7);
  });
});

/* ---------------------------------------------------------- purchase order */

const line = (overrides: Partial<PoLineDraft> = {}): PoLineDraft => ({
  productId: "PRD001",
  name: "Cotton Kurta",
  sku: "DCZ-WO0001",
  supplierSku: "AT-K-01",
  quantity: "50",
  unitCost: "450",
  taxRate: "",
  moq: 10,
  ...overrides,
});

const po = (overrides: Partial<PoDraft> = {}): PoDraft => ({
  supplierId: "SUP001",
  lines: [line()],
  expectedAt: "2026-10-15",
  supplierReference: " Q-77 ",
  notes: " Rush ",
  ...overrides,
});

describe("validatePurchaseOrder", () => {
  it("accepts a valid order", () => {
    expect(validatePurchaseOrder(po())).toEqual({});
  });

  it("needs a supplier and at least one product", () => {
    expect(validatePurchaseOrder(po({ supplierId: "", lines: [] }))).toEqual({ supplierId: "Choose a supplier.", items: "Add at least one product." });
  });

  it("refuses the same product twice", () => {
    expect(validatePurchaseOrder(po({ lines: [line(), line({ quantity: "5" })] })).items).toBe("Cotton Kurta is on this order twice.");
  });

  it.each(["", "0", "-1", "1.5", "abc", String(MAX_QUANTITY + 1)])("rejects a quantity of %j on the line's own key", (quantity) => {
    expect(validatePurchaseOrder(po({ lines: [line(), line({ productId: "PRD002", quantity })] }))).toEqual({
      "items.1.quantity": "A whole number from 1 to 10,00,000.",
    });
  });

  it("accepts the largest quantity", () => {
    expect(validatePurchaseOrder(po({ lines: [line({ quantity: String(MAX_QUANTITY) })] }))).toEqual({});
  });

  it("allows a blank cost for a linked product but not for an unlinked one", () => {
    expect(validatePurchaseOrder(po({ lines: [line({ unitCost: " " })] }))).toEqual({});
    expect(validatePurchaseOrder(po({ lines: [line({ unitCost: "", moq: null })] }))).toEqual({
      "items.0.unitCost": "Enter the unit cost — this product isn't linked to the supplier.",
    });
  });

  it.each(["0", "-2", "1.234", "free"])("rejects a unit cost of %j", (unitCost) => {
    expect(validatePurchaseOrder(po({ lines: [line({ unitCost })] }))["items.0.unitCost"]).toBe("Enter a cost above ₹0.");
  });

  it.each([
    ["", undefined],
    ["0", undefined],
    ["12.5", undefined],
    ["100", undefined],
    ["101", "A percentage from 0 to 100, or blank for the product's rate."],
    ["-5", "A percentage from 0 to 100, or blank for the product's rate."],
    ["GST", "A percentage from 0 to 100, or blank for the product's rate."],
  ])("checks a tax rate of %j", (taxRate, message) => {
    expect(validatePurchaseOrder(po({ lines: [line({ taxRate })] }))["items.0.taxRate"]).toBe(message);
  });
});

describe("toPurchaseOrderInput", () => {
  it("sends numbers, and leaves out a blank cost, tax rate and date", () => {
    expect(
      toPurchaseOrderInput(po({ expectedAt: "", lines: [line({ unitCost: "", quantity: " 12 " }), line({ productId: "PRD002", unitCost: "99.5", taxRate: "12" })] })),
    ).toEqual({
      supplierId: "SUP001",
      items: [
        { productId: "PRD001", quantity: 12 },
        { productId: "PRD002", quantity: 50, unitCost: 99.5, taxRate: 12 },
      ],
      supplierReference: "Q-77",
      notes: "Rush",
    });
  });

  it("includes the expected date when set", () => {
    expect(toPurchaseOrderInput(po()).expectedAt).toBe("2026-10-15");
  });
});

describe("previewSubtotal", () => {
  it("adds quantity × cost over the lines that are complete", () => {
    expect(previewSubtotal([line(), line({ quantity: "3", unitCost: "33.33" }), line({ unitCost: "" }), line({ quantity: "x" }), line({ quantity: "-2" })])).toBe(
      22500 + 99.99,
    );
  });

  it("is zero with nothing to add", () => {
    expect(previewSubtotal([])).toBe(0);
  });
});

/* --------------------------------------------------------------- receiving */

const receiptLine = (overrides: Partial<ReceiptLineDraft> = {}): ReceiptLineDraft => ({
  poItemId: 1,
  name: "Cotton Kurta",
  outstanding: 50,
  received: "",
  damaged: "",
  rejected: "",
  note: "",
  ...overrides,
});

const receipt = (overrides: Partial<ReceiptDraft> = {}): ReceiptDraft => ({
  receivedAt: "2026-10-02",
  notes: "",
  lines: [receiptLine({ received: "20" })],
  allowOverReceipt: false,
  overReceiptReason: "",
  ...overrides,
});

const TODAY = "2026-10-02";

describe("validateReceipt", () => {
  it("accepts a valid delivery", () => {
    expect(validateReceipt(receipt(), TODAY)).toEqual({});
    expect(validateReceipt(receipt({ receivedAt: "" }), TODAY)).toEqual({});
  });

  it("refuses a received date in the future", () => {
    expect(validateReceipt(receipt({ receivedAt: "2026-10-03" }), TODAY)).toEqual({ receivedAt: "The received date can't be in the future." });
  });

  it("needs something received on at least one line", () => {
    expect(validateReceipt(receipt({ lines: [receiptLine(), receiptLine({ poItemId: 2, received: "0" })] }), TODAY)).toEqual({
      items: "Enter a received quantity for at least one line.",
    });
  });

  it.each([
    ["20", "1", "0", undefined],
    ["20", "10", "10", undefined],
    ["20", "11", "10", "Damaged and rejected can't be more than received."],
    ["20", "21", "", "Damaged and rejected can't be more than received."],
    ["5", "", "6", "Damaged and rejected can't be more than received."],
  ])("received %s, damaged %j, rejected %j", (received, damaged, rejected, message) => {
    const errors = validateReceipt(receipt({ lines: [receiptLine({ received, damaged, rejected })] }), TODAY);
    expect(errors["items.0.damagedQty"]).toBe(message);
  });

  it("flags damage reported on a line with nothing received", () => {
    const errors = validateReceipt(receipt({ lines: [receiptLine({ received: "10" }), receiptLine({ poItemId: 2, damaged: "1" })] }), TODAY);
    expect(errors).toEqual({ "items.1.damagedQty": "Damaged and rejected can't be more than received." });
  });

  it.each([
    ["receivedQty", { received: "1.5" }],
    ["damagedQty", { received: "5", damaged: "-1" }],
    ["rejectedQty", { received: "5", rejected: "two" }],
  ] as const)("asks for whole numbers in %s", (field, patch) => {
    const errors = validateReceipt(receipt({ lines: [receiptLine(patch)] }), TODAY);
    expect(errors[`items.0.${field}`]).toBe("A whole number, 0 or more.");
    // A malformed line isn't checked any further.
    expect(errors["items.0.damagedQty"] === undefined || field === "damagedQty").toBe(true);
  });

  it("refuses more than is outstanding unless over-receipt is allowed, with a reason", () => {
    const over = receipt({ lines: [receiptLine({ received: "51" })] });
    expect(validateReceipt(over, TODAY)).toEqual({
      "items.0.receivedQty": "Only 50 outstanding. Tick “allow over-receipt” to accept more.",
    });
    expect(validateReceipt({ ...over, allowOverReceipt: true }, TODAY)).toEqual({
      overReceiptReason: "Say why more than ordered is being accepted.",
    });
    expect(validateReceipt({ ...over, allowOverReceipt: true, overReceiptReason: "Supplier sent extra" }, TODAY)).toEqual({});
    expect(validateReceipt(receipt({ lines: [receiptLine({ received: "50" })] }), TODAY)).toEqual({});
  });
});

describe("toReceiptInput and acceptedOf", () => {
  it("sends only lines with something on them, as numbers, with the idempotency key", () => {
    const input = toReceiptInput(
      receipt({
        notes: "  Challan 77 ",
        lines: [
          receiptLine({ received: "20", damaged: "1", note: "  box torn " }),
          receiptLine({ poItemId: 2 }),
          receiptLine({ poItemId: 3, received: "5", rejected: "5" }),
        ],
      }),
      "key-1",
    );
    expect(input).toEqual({
      receivedAt: "2026-10-02",
      notes: "Challan 77",
      idempotencyKey: "key-1",
      items: [
        { poItemId: 1, receivedQty: 20, damagedQty: 1, rejectedQty: 0, note: "box torn" },
        { poItemId: 3, receivedQty: 5, damagedQty: 0, rejectedQty: 5 },
      ],
      allowOverReceipt: false,
    });
  });

  it("sends the over-receipt reason only when over-receipt is allowed, and leaves out a blank date", () => {
    const input = toReceiptInput(receipt({ receivedAt: "", allowOverReceipt: true, overReceiptReason: "  Extra  " }), "k");
    expect(input).not.toHaveProperty("receivedAt");
    expect(input.allowOverReceipt).toBe(true);
    expect(input.overReceiptReason).toBe("Extra");
    expect(toReceiptInput(receipt({ overReceiptReason: "ignored" }), "k")).not.toHaveProperty("overReceiptReason");
  });

  it("works out the accepted quantity, never below zero", () => {
    expect(acceptedOf(receiptLine({ received: "20", damaged: "1", rejected: "2" }))).toBe(17);
    expect(acceptedOf(receiptLine({ received: "" }))).toBe(0);
    expect(acceptedOf(receiptLine({ received: "2", damaged: "5" }))).toBe(0);
  });
});
