"""initial schema

Revision ID: 49a8ba39a143
Revises: 
Create Date: 2026-09-23 21:45:58.407799
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '49a8ba39a143'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_index(op.f('ix_admin_users_role'), 'admin_users', ['role'], unique=False)
    op.create_index(op.f('ix_admin_users_status'), 'admin_users', ['status'], unique=False)
    op.create_table('banners',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.Column('button_text', sa.String(length=80), nullable=False),
    sa.Column('button_link', sa.String(length=255), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('groups', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('collections',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('tagline', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_slug'), 'collections', ['slug'], unique=True)
    op.create_table('coupons',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('per_customer_limit', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_active'), 'coupons', ['active'], unique=False)
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_status'), 'customers', ['status'], unique=False)
    op.create_table('homepage_sections',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('item_limit', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homepage_sections_display_order'), 'homepage_sections', ['display_order'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('href', sa.String(length=255), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_table('setting_documents',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('addresses',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('line1', sa.String(length=255), nullable=False),
    sa.Column('line2', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('pincode', sa.String(length=12), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_customer_id'), 'addresses', ['customer_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('order_number', sa.String(length=30), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('placed_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=40), nullable=False),
    sa.Column('delivery_method', sa.String(length=30), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_delivery', sa.String(length=60), nullable=False),
    sa.Column('tracking_number', sa.String(length=60), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('catalogue_savings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('coupon_code', sa.String(length=40), nullable=True),
    sa.Column('coupon_discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_name', sa.String(length=120), nullable=False),
    sa.Column('shipping_phone', sa.String(length=20), nullable=False),
    sa.Column('shipping_line1', sa.String(length=255), nullable=False),
    sa.Column('shipping_line2', sa.String(length=255), nullable=False),
    sa.Column('shipping_city', sa.String(length=120), nullable=False),
    sa.Column('shipping_state', sa.String(length=120), nullable=False),
    sa.Column('shipping_pincode', sa.String(length=12), nullable=False),
    sa.Column('shipping_country', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index('ix_orders_customer_placed', 'orders', ['customer_id', 'placed_at'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_placed_at'), 'orders', ['placed_at'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status', 'payment_status'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('sku', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('category_id', sa.String(length=20), nullable=False),
    sa.Column('subcategory', sa.String(length=80), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('original_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('material', sa.String(length=160), nullable=False),
    sa.Column('care', sa.Text(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.Column('is_trending', sa.Boolean(), nullable=False),
    sa.Column('is_best_seller', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('reserved_stock', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=40), nullable=False),
    sa.Column('tax_rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('meta_title', sa.String(length=255), nullable=False),
    sa.Column('meta_description', sa.String(length=500), nullable=False),
    sa.Column('updated_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_discount'), 'products', ['discount'], unique=False)
    op.create_index('ix_products_flags', 'products', ['is_new', 'is_trending', 'is_best_seller', 'is_featured'], unique=False)
    op.create_index('ix_products_listing', 'products', ['status', 'category_id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_index(op.f('ix_products_subcategory'), 'products', ['subcategory'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('size', sa.String(length=30), nullable=False),
    sa.Column('color', sa.String(length=60), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'product_id', 'size', 'color', name='uq_cart_variant')
    )
    op.create_index(op.f('ix_cart_items_customer_id'), 'cart_items', ['customer_id'], unique=False)
    op.create_index(op.f('ix_cart_items_product_id'), 'cart_items', ['product_id'], unique=False)
    op.create_table('collection_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'product_id', name='uq_collection_product')
    )
    op.create_index(op.f('ix_collection_products_collection_id'), 'collection_products', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_products_product_id'), 'collection_products', ['product_id'], unique=False)
    op.create_table('coupon_usages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coupon_id', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('order_id', sa.String(length=20), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupon_usages_coupon_id'), 'coupon_usages', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_coupon_usages_customer_id'), 'coupon_usages', ['customer_id'], unique=False)
    op.create_index(op.f('ix_coupon_usages_order_id'), 'coupon_usages', ['order_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('invoice_number', sa.String(length=40), nullable=False),
    sa.Column('order_id', sa.String(length=20), nullable=False),
    sa.Column('order_number', sa.String(length=30), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('billing_address', sa.JSON(), nullable=False),
    sa.Column('shipping_address', sa.JSON(), nullable=False),
    sa.Column('place_of_supply', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.BigInteger(), nullable=False),
    sa.Column('product_discount', sa.BigInteger(), nullable=False),
    sa.Column('coupon_code', sa.String(length=40), nullable=True),
    sa.Column('coupon_discount', sa.BigInteger(), nullable=False),
    sa.Column('shipping', sa.BigInteger(), nullable=False),
    sa.Column('other_charges', sa.BigInteger(), nullable=False),
    sa.Column('taxable_amount', sa.BigInteger(), nullable=False),
    sa.Column('tax_mode', sa.String(length=20), nullable=False),
    sa.Column('tax_rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst', sa.BigInteger(), nullable=False),
    sa.Column('sgst', sa.BigInteger(), nullable=False),
    sa.Column('igst', sa.BigInteger(), nullable=False),
    sa.Column('total_tax', sa.BigInteger(), nullable=False),
    sa.Column('prices_include_tax', sa.Boolean(), nullable=False),
    sa.Column('grand_total', sa.BigInteger(), nullable=False),
    sa.Column('amount_paid', sa.BigInteger(), nullable=False),
    sa.Column('amount_refunded', sa.BigInteger(), nullable=False),
    sa.Column('payment_id', sa.String(length=20), nullable=True),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('terms', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index('ix_invoices_customer_issued', 'invoices', ['customer_id', 'issued_at'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_issued_at'), 'invoices', ['issued_at'], unique=False)
    op.create_index(op.f('ix_invoices_order_id'), 'invoices', ['order_id'], unique=False)
    op.create_index(op.f('ix_invoices_payment_id'), 'invoices', ['payment_id'], unique=False)
    op.create_index('ix_invoices_status', 'invoices', ['status', 'payment_status'], unique=False)
    op.create_table('order_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=40), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_events_order_id'), 'order_events', ['order_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sku', sa.String(length=60), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.Column('size', sa.String(length=30), nullable=True),
    sa.Column('color', sa.String(length=60), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_table('product_colors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('hex', sa.String(length=9), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_colors_product_id'), 'product_colors', ['product_id'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.create_table('product_sizes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_sizes_product_id'), 'product_sizes', ['product_id'], unique=False)
    op.create_table('product_specifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_specifications_product_id'), 'product_specifications', ['product_id'], unique=False)
    op.create_table('product_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('tag', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'tag', name='uq_product_tag')
    )
    op.create_index(op.f('ix_product_tags_product_id'), 'product_tags', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_tags_tag'), 'product_tags', ['tag'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=True),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('verified_purchase', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'customer_id', 'title', name='uq_review_once')
    )
    op.create_index(op.f('ix_reviews_customer_id'), 'reviews', ['customer_id'], unique=False)
    op.create_index(op.f('ix_reviews_product_id'), 'reviews', ['product_id'], unique=False)
    op.create_index(op.f('ix_reviews_status'), 'reviews', ['status'], unique=False)
    op.create_index(op.f('ix_reviews_submitted_at'), 'reviews', ['submitted_at'], unique=False)
    op.create_table('stock_adjustments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('quantity_before', sa.Integer(), nullable=False),
    sa.Column('quantity_after', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('actor', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_adjustments_created_at'), 'stock_adjustments', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_adjustments_product_id'), 'stock_adjustments', ['product_id'], unique=False)
    op.create_table('wishlist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'product_id', name='uq_wishlist_product')
    )
    op.create_index(op.f('ix_wishlist_items_customer_id'), 'wishlist_items', ['customer_id'], unique=False)
    op.create_index(op.f('ix_wishlist_items_product_id'), 'wishlist_items', ['product_id'], unique=False)
    op.create_table('credit_notes',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('credit_note_number', sa.String(length=40), nullable=False),
    sa.Column('invoice_id', sa.String(length=20), nullable=False),
    sa.Column('invoice_number', sa.String(length=40), nullable=False),
    sa.Column('order_id', sa.String(length=20), nullable=False),
    sa.Column('order_number', sa.String(length=30), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('refund_id', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('tax', sa.BigInteger(), nullable=False),
    sa.Column('total', sa.BigInteger(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_notes_credit_note_number'), 'credit_notes', ['credit_note_number'], unique=True)
    op.create_index(op.f('ix_credit_notes_customer_id'), 'credit_notes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_credit_notes_invoice_id'), 'credit_notes', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_credit_notes_issued_at'), 'credit_notes', ['issued_at'], unique=False)
    op.create_index(op.f('ix_credit_notes_order_id'), 'credit_notes', ['order_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sku', sa.String(length=60), nullable=False),
    sa.Column('hsn', sa.String(length=12), nullable=False),
    sa.Column('size', sa.String(length=30), nullable=True),
    sa.Column('color', sa.String(length=60), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.BigInteger(), nullable=False),
    sa.Column('line_subtotal', sa.BigInteger(), nullable=False),
    sa.Column('discount', sa.BigInteger(), nullable=False),
    sa.Column('taxable_amount', sa.BigInteger(), nullable=False),
    sa.Column('tax_rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst', sa.BigInteger(), nullable=False),
    sa.Column('sgst', sa.BigInteger(), nullable=False),
    sa.Column('igst', sa.BigInteger(), nullable=False),
    sa.Column('tax', sa.BigInteger(), nullable=False),
    sa.Column('line_total', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_product_id'), 'invoice_items', ['product_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('transaction_id', sa.String(length=60), nullable=False),
    sa.Column('order_id', sa.String(length=20), nullable=False),
    sa.Column('order_number', sa.String(length=30), nullable=False),
    sa.Column('invoice_id', sa.String(length=20), nullable=False),
    sa.Column('invoice_number', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('refunded_amount', sa.BigInteger(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_reference', sa.String(length=120), nullable=True),
    sa.Column('instrument_hint', sa.String(length=60), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_created_at_utc'), 'payments', ['created_at_utc'], unique=False)
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index('ix_payments_status_created', 'payments', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    op.create_table('payment_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_events_payment_id'), 'payment_events', ['payment_id'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('refund_number', sa.String(length=40), nullable=False),
    sa.Column('order_id', sa.String(length=20), nullable=False),
    sa.Column('order_number', sa.String(length=30), nullable=False),
    sa.Column('invoice_id', sa.String(length=20), nullable=False),
    sa.Column('invoice_number', sa.String(length=40), nullable=False),
    sa.Column('payment_id', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('credit_note_id', sa.String(length=20), nullable=True),
    sa.Column('initiated_by', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_customer_id'), 'refunds', ['customer_id'], unique=False)
    op.create_index(op.f('ix_refunds_invoice_id'), 'refunds', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_refunds_order_id'), 'refunds', ['order_id'], unique=False)
    op.create_index(op.f('ix_refunds_payment_id'), 'refunds', ['payment_id'], unique=False)
    op.create_index(op.f('ix_refunds_refund_number'), 'refunds', ['refund_number'], unique=True)
    op.create_index(op.f('ix_refunds_requested_at'), 'refunds', ['requested_at'], unique=False)
    op.create_index(op.f('ix_refunds_status'), 'refunds', ['status'], unique=False)
    op.create_table('refund_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('refund_id', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['refund_id'], ['refunds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refund_items_refund_id'), 'refund_items', ['refund_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refund_items_refund_id'), table_name='refund_items')
    op.drop_table('refund_items')
    op.drop_index(op.f('ix_refunds_status'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_requested_at'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_refund_number'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_payment_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_order_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_invoice_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_customer_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_payment_events_payment_id'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index('ix_payments_status_created', table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at_utc'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_invoice_items_product_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_credit_notes_order_id'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_issued_at'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_invoice_id'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_customer_id'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_credit_note_number'), table_name='credit_notes')
    op.drop_table('credit_notes')
    op.drop_index(op.f('ix_wishlist_items_product_id'), table_name='wishlist_items')
    op.drop_index(op.f('ix_wishlist_items_customer_id'), table_name='wishlist_items')
    op.drop_table('wishlist_items')
    op.drop_index(op.f('ix_stock_adjustments_product_id'), table_name='stock_adjustments')
    op.drop_index(op.f('ix_stock_adjustments_created_at'), table_name='stock_adjustments')
    op.drop_table('stock_adjustments')
    op.drop_index(op.f('ix_reviews_submitted_at'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_status'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_product_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_customer_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_product_tags_tag'), table_name='product_tags')
    op.drop_index(op.f('ix_product_tags_product_id'), table_name='product_tags')
    op.drop_table('product_tags')
    op.drop_index(op.f('ix_product_specifications_product_id'), table_name='product_specifications')
    op.drop_table('product_specifications')
    op.drop_index(op.f('ix_product_sizes_product_id'), table_name='product_sizes')
    op.drop_table('product_sizes')
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_product_colors_product_id'), table_name='product_colors')
    op.drop_table('product_colors')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_order_events_order_id'), table_name='order_events')
    op.drop_table('order_events')
    op.drop_index('ix_invoices_status', table_name='invoices')
    op.drop_index(op.f('ix_invoices_payment_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_order_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_issued_at'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index('ix_invoices_customer_issued', table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_coupon_usages_order_id'), table_name='coupon_usages')
    op.drop_index(op.f('ix_coupon_usages_customer_id'), table_name='coupon_usages')
    op.drop_index(op.f('ix_coupon_usages_coupon_id'), table_name='coupon_usages')
    op.drop_table('coupon_usages')
    op.drop_index(op.f('ix_collection_products_product_id'), table_name='collection_products')
    op.drop_index(op.f('ix_collection_products_collection_id'), table_name='collection_products')
    op.drop_table('collection_products')
    op.drop_index(op.f('ix_cart_items_product_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_customer_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_products_subcategory'), table_name='products')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index('ix_products_listing', table_name='products')
    op.drop_index('ix_products_flags', table_name='products')
    op.drop_index(op.f('ix_products_discount'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_table('products')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index(op.f('ix_orders_placed_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index('ix_orders_customer_placed', table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_addresses_customer_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_table('setting_documents')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_homepage_sections_display_order'), table_name='homepage_sections')
    op.drop_table('homepage_sections')
    op.drop_index(op.f('ix_customers_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_active'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_collections_slug'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_table('categories')
    op.drop_table('banners')
    op.drop_index(op.f('ix_admin_users_status'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_role'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
